### ISSUE TITLE
little bug

### ISSUE THREAD

**Issue by nonameboy007** [kiddac/XStreamity#1]
Hello Kiddac,

First of all, thanks for your hardest work. Really awesome plugins.

I noticed that between version 1.16 and those that followed, a problem occured.

Indeed, in version 1.16:

- it was possible to return to the movie after pressed back button , in versions after 1.16, the movie begins again.

- It was possible to put next or previous with the P + / P- buttons, but it works badly now after 1.16. (occured in series)

Thanks

**Comment by BliNeR-KeY** [comment]
hello try dhis one

[streamplayer.zip](https://github.com/kiddac/XStreamity/files/4829975/streamplayer.zip)

**Comment by nonameboy007** [comment]
Awesome,  its working now 

Thanks a lot
