### ISSUE TITLE
UI is larger than screen

### ISSUE THREAD

**Issue by jbx1** [kiddac/XStreamity#13]
For some reason the UI of xstreamity is rendering larger than the screen, cutting off the names of the items from the left side and the title and date from the top.

This was observed on vu solo2 on both Blackhole and OpenATV, on different TVs (LG and Panasonic).

See attached. 
![image](https://user-images.githubusercontent.com/6760528/140549522-8fc2c562-4b9d-4b46-abc4-c1d8c7648136.png)

**Comment by kiddac** [comment]
TV PICTURE SETTINGS
1) turn off overscan on your tv picture settings. 
2) or set TV screen picture settings to screen fit.

ENIGMA2 BOX SETTINGS
3) Adjust your screen size via openatv settings. 
Menu > setup > usage & user interface > extended user interface > osd position

**Comment by jbx1** [comment]
Great I confirm this solves it:

On Panasonic TVs, 16:9 Overscan needs to be turned off. 
On LG TVs, JustScan must be ON. 

For some reason they are the opposite by default, which crops the input. 

Might be useful to add this information to the Help / FAQs.
