### ISSUE TITLE
Category at Search

### ISSUE THREAD

**Issue by Hannes0009** [kiddac/XStreamity#16]
Hey, is it possible to implement it, that when you look for some movie via search, you get the hits and then you get show in which category the seperate hit is ?

**Comment by kiddac** [comment]
The only current way to do this is to select the ALL category. 
The categories are step by step, so it doesnt see what is in the other categories unless in the "ALL" catergory. Which can be slow if large

**Comment by carpediem2309** [comment]
and it makes me wonder how do i put this links into a kodi look really i don know 
btw i have download the enigma2 onto my pvr but i dont know really i can be smart  and googe it meybe i will butt i am sking an expert so olizz if you can hellp me
