### ISSUE TITLE
Audio / Subs in X-Streamity

### ISSUE THREAD

**Issue by hk1312** [kiddac/XStreamity#18]
Hi,
first of all I want to thank you for the stunning plugin for enigma2 devices.
This is not an issue. The plugin functions very well on my enigma2 set top box.
I have a feature request for your plugin: Is it possible to add the audio and subs menu to the yellow button during the playback of a  stream ? The yellow button hasn't got any function during playback, right ? My remote hasn't got an extra audio button, so I'm not able to choose both menus during playback. Thank you.
If you submit your paypal address I'll made a contribution.
Regards
HK

**Comment by kiddac** [comment]
What image are you using. This is already built in for most oe-alliace images as it uses the component infobaraudiosupport, and infobarsubtitlessupport

Subtitles will only appear if included in stream as shown by the subs icon in the infobar.
If using VOD and you have subsupports plugin, the subs button will open subssupport plugin. (subs support plugin needs to also be turned on in xstreamity settings.

You are better asking for requests or reporting issues in my main forum thread. You will get a quicker response as I rarely visit github. Also there are many other users who will share their knowledge and experiences. 

https://www.linuxsat-support.com/thread/147664-x-streamity-xtream-codes-iptv-player-new-thread/

![image](https://user-images.githubusercontent.com/6818561/158075221-c3faadd6-b367-4123-be6b-69b199e01c7f.png)
