### ISSUE TITLE
Custom location for the xstreamity files

### ISSUE THREAD

**Issue by neoatomic** [kiddac/XStreamity#2]
Just started using the plugin, and wanted to give some feedback.

My intention was to store all the xstreamity config files in a single location to keep the main enigma2 folder as clean as possible. 
That location was "etc\enigma2\e2m3u2bouquet\xstreamity\"

But the x-playlists.json always gets created in etc\enigma2\xstreamity\ .
Also a etc\enigma2\epg\ folder gets created.

So that defended my intention to put all the xstreamity files in a single custom location.

Also if you set a custom location with more characters than standard entry the text in the GUI overplaps. See attached screenshot. 

![1_0_19_4CCD_81A_600_FFFF0000_0_0_0_20200812120958](https://user-images.githubusercontent.com/7928052/90004559-5f8c1b00-dc85-11ea-8732-162b6ed66839.jpg)

Noting to serious, but hope you find some time in the future to maybe look into this.
Thanks for providing us with this cool plugin. ;)

```
[ActionMap] Keymap 'XStreamityActions' -> Action = 'cancel'.
Traceback (most recent call last):
  File "/usr/lib/enigma2/python/Components/ActionMap.py", line 58, in action
    res = self.actions[action]()
  File "/usr/lib/enigma2/python/Plugins/Extensions/XStreamity/menu.py", line 219, in quit
    self.writeJsonFile()
  File "/usr/lib/enigma2/python/Plugins/Extensions/XStreamity/menu.py", line 170, in writeJsonFile
    self.playlists_all = json.load(f)
  File "/usr/lib/python3.8/json/__init__.py", line 293, in load
    return loads(fp.read(),
  File "/usr/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.8/json/decoder.py", line 340, in decode
    raise JSONDecodeError("Extra data", s, end)
json.decoder.JSONDecodeError: Extra data: line 1 column 1602 (char 1601)
```

**Comment by kiddac** [comment]
The reason that folder choice option was put in was because a lot of my users have both xstreamity and JediMakerXtream installed on their boxes and wanted to share the same playlists.txt file rather than have 2. 

if you want to manually change the location, I think you can just change this in the plugin.py file. I have not tested this though. 

dir_dst = "/etc/enigma2/xstreamity/"
