### ISSUE TITLE
Certain playlist gives user/pass error except when editing playlist.txt directly

### ISSUE THREAD

**Issue by BlackTiger63** [kiddac/XStreamity#20]
First of all, thank you for this great work.
It's really the best tool around for Enigma2 receivers imho.

Found a very odd bug.

So we got playlist lines working. No issues on Smart TV and Android boxes with same credentials. But on VU+ boxes, maybe others, an issue occurs.

Maybe it's because a port below 1024 is used, I don't know. This is an example from a working line in playlist.txt:
`http://somiptv.com:27300/get.php?username=123SomeUSer&password=Q12SomePAss&type=m3u&output=ts #IPTV`
This was filled in via the GUI by just using username, pass and url like it should be done, no direct edits. And no issues.

Now we have another one and fill this in using the GUI.
http
anotheriptv.com
port 88
user 17THISUSER2
pass HIS320PASS
and then continuously the error notices appeared dat the data is invalid or i'm not authorised.

Now I tried something else. I editted the /etc/enigma2/xstreamity/playlist.txt file directly via telnet and added exact the same data like this.
`http://anotheriptv.com:88/get.php?username=17THISUSER2&password=HIS320PASS&type=m3u&output=ts #IPTV`

I save the file, start xstreamity and now it shows the playlist available and green light. I click on it and everything is working.

So entering the same data via the Xstreamity GUI in the receiver, only for this specific line, it does not work, but do I put the same line exactly the same in the playlist.txt then it's working fine.

Tested on multiple VU+ receivers, also brand new, without any other lines present. I had no way to test other brands.
 
So how come via the GUI only for this line, the error appears, and when putting it directly in the playlist.txt it does work without problems.
Could this have something to do with the use of port 88 or why? Seems a bug to me.

**Comment by kiddac** [comment]
Not had any complaints of late that the plugin add line is not working. 
I am a little confused by your post though. If you use the plugin to enter the line, this then gets written to playlists.txt file.
So if you have opened that file, you should see this entry. 
You can then physically see if its become corrupted or not and why it is different than what you have manually typed in. 
It might even just be an unknown space added before or after the data you have entered. 

It is easier if you ftp or use windows network drive to open this playlists.txt file. 

Please visit linuxsat for questions regarding my plugins. I am on there every day, where as I don't check github that often
https://www.linuxsat-support.com/thread/147664-x-streamity-xtream-codes-iptv-player-new-thread/

**Comment by BlackTiger63** [comment]
Hello Kiddac.
I normally also have no problems at all, only with this one line. For some reason, this specific line does not get written to the playlist.txt file because it generates that error.
So when starting Xstreamity again, all is empty and you have to enter it newly. So that is the odd thing.
There is no space or anything, we tried of 3 different people, triplechecking if all was correct and on several receivers. Credentials are 100% correct.

Really all other lines are correct without any issues. We never had problems before, so that is why this is such an odd issue.
I'll give it a try on Linux-sat support, maybe others have seen this before too.

**Comment by kiddac** [comment]
The port isn't an issue, but has your username or password got any special characters in like @ or : or other special symbols

**Comment by BlackTiger63** [comment]
No that's also the odd thing, nothing special, it's 13 characters username and 13 characters password, only containing like normal characters and numbers like AQD6 but all in capital.

I just tried again and the playlist.txt is not even filled with anything. Only the error occurs when pushing the green button "data invalid or not authorised". Same credentials via console in the playlist.txt and working.
I tried with m3u and I tried with ts in the GUI but that does not make any difference.
The line in the playlist.txt (when I put it in there) ends with
`&type=m3u&output=ts `
just like other working lines.


I just posted on linuxsat-support also but it must be approved by a moderator.

**Comment by kiddac** [comment]
This issue should be fixed now in later versions. 
There was a problem with redirects in adding playlists via the GUI. This redirect issue was already addressed if the url was downloaded from the playlists.txt file. So that is why one method worked but the other didn't
I think I have fixed this now, so would be good if you could test your problem playlist and confirm

**Comment by BlackTiger63** [comment]
I just had time to upgrade to version 3.69 and test it for you.
And I can confirm that you fixed the issue. The "problem" provider could now be added and removed without any issues.
So I will close this issue as fixed.

Thanks for your great support!
