### ISSUE TITLE
Option to define location for epg.json

### ISSUE THREAD

**Issue by hjgode** [kiddac/XStreamity#27]
I would like to have an option to define the storage location of the epg.xml.

By default it is saved to /etc/enigma2/xstreamity/epg/provider-name

As this is part of my ubirootfs (the small flash), I did manually move the provider-name folder to external media and created a symbolic link to the dir. My last epg.json was 194MB and crashes the VuPlus Solo2!

**Comment by kiddac** [comment]
??? there is a setting for this already 

![image](https://user-images.githubusercontent.com/6818561/197599830-d52c92ec-dcf3-4065-aba5-9edf9a66be7d.png)
