### ISSUE TITLE
Series favourites?

### ISSUE THREAD

**Issue by keesje9** [kiddac/XStreamity#29]
first of all you make great plugins for iptv really great!! where can i make a donation for all your hard work?

request for favorites in series so you don't have to keep searching where you left off

**Comment by kiddac** [comment]
Favourites is not easy to do with series
It gets requested a lot. I always have to say no. 
But I have never said never. 

I don't come on github a lot. My home is here
https://www.linuxsat-support.com/board/1462-enigma2-kiddac/

My paypal beer kitty is this
https://paypal.me/kiddac
