### ISSUE TITLE
Suggestions and Requests 

### ISSUE THREAD

**Issue by Insprion80** [kiddac/XStreamity#31]
Hello Kiddac,
Really appreciate your development efforts for xstreamity, I would like to share with you some thoughts, you might use it in your development plan for this plugin.

1. Plugin Login Page.
Is it possible to add option to select one account as primary account so once start to plugin login directly into it with option to swap that account in main page (add account switch button 🔳 will be great)

2. Once you login there are a page with live, vod etc for login account, can you add another button 🔳 for switch between live, vod and series, Inside the account page (I think add ascond buttons bar will be great include more swap functions)

(addition of second function bar on the top include category name, date/time, account swap will be great with some icons)

3. Catagories list, is it possible to add norther list for content? So select live category with show primary vertical list on the left include the main subcategories then secondary list right to it with the content of it.

I would like to suggest more but again it just thoughts want to share it with you,

Again appreciate your time and efforts

**Comment by Insprion80** [comment]
![images (12)](https://user-images.githubusercontent.com/110155731/214991703-c7b6d530-1850-4b74-b7ba-10a21af1c5dc.jpeg)
![images (11)](https://user-images.githubusercontent.com/110155731/214991705-ea1db737-9c71-4706-b158-609416770b6b.jpeg)
![images (10)](https://user-images.githubusercontent.com/110155731/214991706-ba17cf88-fac4-41f0-a45e-4c56e6286c5d.jpeg)

**Comment by kiddac** [comment]
1) login page. I actually started rewriting this plugin to be more like an android app. Where first screen is enter details. Then just load last default playlist. Everything else would be via a menu button, or other buttons.  I then ended up hospitalised through illness and it never got finished. It isn't actually that difficult and very little new code is needed. But its just finding the time to do it. I have lots of projects on the go. Its on the future to do list. But xstreamity is in a good place, so its low on the priority list. 

Multiple lists are a problematic as the api I use for this is step by step based. You get the categories. You then get the streams from that category. You have to do a server call every time you highlight a different category. This is actually dangerous and can get you blocked if you do too many server calls in quick succession. There are ways around it by putting in delays. But I understand your point. 
Enigma2 is also not as powerful or has the temp storage space as android devices. My plugin is meant to work on most boxes, not just the latest quad core boxes.

**Comment by Insprion80** [comment]
well done kiddac, i am not sure if you are open for more suggestions....
