### ISSUE TITLE
Request

### ISSUE THREAD

**Issue by Tomiliy** [kiddac/XStreamity#32]
Hello, 
this is not a mistake, but a suggestion.
I have been using Streamity for quite a while.
What I would really like is if you could create your own lists that are parts of the existing ones. So that you can put together your own favourite stations there. (I don't mean favourites)

And the second wish would be an EPG overview as a timeline. Not only now and immediately, but also 10 days in advance, or an EPG search without having to be in All.
Thank you

**Comment by kiddac** [comment]
IF you mean a list for different providers. To much hassle. 
If you don't mean favourites folder. Then I am confused. Unless you want to do this in a text editor before entering the plugin. 

The EPG does have a full list. Long press the EPG button to get the full list. (although some providers have broken this functionality using old hacked xtream apis).

 It is never going to be a sidewards timeline like enigma2 epg though. Thats far to much work.
