### ISSUE TITLE
Please add reconnect for stopped stream and font size...

### ISSUE THREAD

**Issue by Paderman** [kiddac/XStreamity#36]
Hello,
it would be very nice, if following can be added:

- If stream is stopped (freezes), it would be very nice, if can automatically restarted
- Settings for font size, because sometimes the font is very small
- Settings for buffering, e.g. 30 seconds, if possible. Service App doesn't really do it

Thank you in advance 🙂

**Comment by jenson89** [comment]
the reconnect button is exaktly what im searching too!
would be an amazing feature.

**Comment by kiddac** [comment]
I tried my own version of restarting streams but its complicated. There is no guaranteed way to check when a stream has frozen. All the stream types act differently. 1, 4097, 5001, 5002 etc. 
There is a plugin called quarterpounder that tries to start frozen streams. Install that and try it.

I don't know how small your tv is or what skin you are using, but the font shouldn't be small. 

We did try an experimental buffering option in my jedi maker xtream plugin. Personally I found it made zero difference.

**Comment by kiddac** [comment]
i have just put in a very basic stream restart using the zero button on your remote. Its probably better than the complicated automation process anyway, 
I will do a new release very shortly.

**Comment by luxorko** [comment]
would be also nice to have pop up message "stream not avaible" when stream not starting after changing channel or restart., instead black screen

**Comment by jenson89** [comment]
> i have just put in a very basic stream restart using the zero button on your remote. Its probably better than the complicated automation process anyway, 
> 
> I will do a new release very shortly. 

that would be enough, you plan that restart zero button on the next version i guess? because actually on the zero button nothing happens
