### ISSUE TITLE
Enigma2 crash on series opening seaon

### ISSUE THREAD

**Issue by jackchoui** [kiddac/XStreamity#37]
I have a problem with playing serie. I can navigate to the serie en open it. But wehen pressed ok on the season, box crahes. This hapens with older and newest version.

Playing live tv and vod works fine.

this line comes from 1-stream panel. it uses the xc api

crahslog from enigma2

Code
Force rtmp protocol implementation
file: [https://xxxxxx:2083/player_api.php?username=xxxx&password=xxx&action=get_series_info&series_id=168888]

15:08:40.7025 [   ] ../../../git/src/serviceapp/extplayer.cpp:557 recvStopped PlayerBackend::recvStopped - retval = 0
15:08:40.7026 [   ] base/ebase.cpp:280 processOneEvent [eMainloop::processOneEvent] unhandled POLLERR/HUP/NVAL for fd 44(16)
15:08:40.7026 [   ] ../../../git/src/serviceapp/extplayer.cpp:482 gotMessage PlayerBackend::gotMessage - stop
15:08:40.7027 [   ] ../../../git/src/serviceapp/serviceapp.cpp:605 gotExtPlayerMessage eServiceApp::gotExtPlayerMessage - stop
15:08:40.7027 [   ] ../../../git/src/serviceapp/extplayer.cpp:534 thread_finished PlayerBackend::thread_finished
15:08:40.7031 [   ] ../../../git/src/serviceapp/serviceapp.cpp:766 stop eServiceApp::stop
15:08:40.7078 {   } /usr/lib/python2.7/site-packages/twisted/python/util.py:815 untilConcludes 2023-11-23 15:08:40+0100 [-] playing 5002:0:0:0:0:0:0:0:0:0:https%3a//xxxxxx:2083/player_api.php?username=xxxx&password=xxx&action=get_series_info&series_id=168888:Season 1
15:08:40.7085 [   ] ../../../git/src/serviceapp/exteplayer3.cpp:131 ExtEplayer3 ExtEplayer3::ExtEplayer3 initializing with options:
15:08:40.7086 [   ] ../../../git/src/serviceapp/exteplayer3.cpp:124 print  aac_swdec                      = 0
15:08:40.7086 [   ] ../../../git/src/serviceapp/exteplayer3.cpp:124 print  ac3_swdec                      = 0
15:08:40.7087 [   ] ../../../git/src/serviceapp/exteplayer3.cpp:124 print  audio_id                       = not set
15:08:40.7087 [   ] ../../../git/src/serviceapp/exteplayer3.cpp:124 print  audio_uri                      = not set
15:08:40.7087 [   ] ../../../git/src/serviceapp/exteplayer3.cpp:124 print  dash_audio_id                  = not set
15:08:40.7088 [   ] ../../../git/src/serviceapp/exteplayer3.cpp:124 print  dash_video_id                  = not set
15:08:40.7088 [   ] ../../../git/src/serviceapp/exteplayer3.cpp:124 print  downmix                        = 1
15:08:40.7088 [   ] ../../../git/src/serviceapp/exteplayer3.cpp:124 print  dts_swdec                      = 0
15:08:40.7089 [   ] ../../../git/src/serviceapp/exteplayer3.cpp:124 print  eac3_swdec                     = 0
15:08:40.7089 [   ] ../../../git/src/serviceapp/exteplayer3.cpp:124 print  ffmpeg_option                  = not set
15:08:40.7089 [   ] ../../../git/src/serviceapp/exteplayer3.cpp:124 print  flv2mpeg4                      = not set
15:08:40.7090 [   ] ../../../git/src/serviceapp/exteplayer3.cpp:124 print  live_ts                        = not set
15:08:40.7090 [   ] ../../../git/src/serviceapp/exteplayer3.cpp:124 print  loop                           = not set
15:08:40.7090 [   ] ../../../git/src/serviceapp/exteplayer3.cpp:124 print  lpcm_injection                 = 0
15:08:40.7091 [   ] ../../../git/src/serviceapp/exteplayer3.cpp:124 print  mp3_swdec                      = 0
15:08:40.7091 [   ] ../../../git/src/serviceapp/exteplayer3.cpp:124 print  mpegts_program_id              = not set
15:08:40.7091 [   ] ../../../git/src/serviceapp/exteplayer3.cpp:124 print  nice                           = not set
15:08:40.7091 [   ] ../../../git/src/serviceapp/exteplayer3.cpp:124 print  no_pcm_resampling              = not set
15:08:40.7092 [   ] ../../../git/src/serviceapp/exteplayer3.cpp:124 print  progressive                    = not set
15:08:40.7092 [   ] ../../../git/src/serviceapp/exteplayer3.cpp:124 print  rtmpproto                      = 0
15:08:40.7092 [   ] ../../../git/src/serviceapp/exteplayer3.cpp:124 print  subtitle_id                    = not set
15:08:40.7093 [   ] ../../../git/src/serviceapp/exteplayer3.cpp:124 print  wma_swdec                      = 0
15:08:40.7206 [ E ] ../../../git/src/serviceapp/serviceapp.cpp:341 fillSubservices eServiceApp::fillSubservices - failed to retrieve subservices, not supported url
15:08:40.7251 [   ] ../../../git/src/serviceapp/extplayer.cpp:420 gotMessage PlayerBackend::gotMessage - tStart
PlayerApp::processStart: exteplayer3 "https://xxxxxx:2083/player_api.php?username=xxxx&password=xxx&action=get_series_info&series_id=168888" -a 0 -s -n 0 
15:08:40.7330 [   ] driver/rcinput.cpp:38 handleCode [eRCDeviceInputDev] 1 160 1
15:08:40.7354 [   ] ../../../git/src/serviceapp/extplayer.cpp:72 stderrAvail PlayerApp::stderrAvail: {"EPLAYER3_EXTENDED":{"version":68}}

15:08:40.7355 [   ] ../../../git/src/serviceapp/extplayer.cpp:8 handleJsonStr PlayerApp::handleJsonStr: {"EPLAYER3_EXTENDED":{"version":68}}
15:08:40.7355 [   ] ../../../git/src/serviceapp/exteplayer3.cpp:410 handleJsonOutput ExtEPlayer3::handleJsonOutput - unhandled key "EPLAYER3_EXTENDED"
15:08:40.7357 {   } /usr/lib/python2.7/site-packages/twisted/python/util.py:815 untilConcludes 2023-11-23 15:08:40+0100 [-] KEY: 352 0 KEY_OK OK
15:08:40.7368 {   } /usr/lib/python2.7/site-packages/twisted/python/util.py:815 untilConcludes 2023-11-23 15:08:40+0100 [-] [ActionMap] Keymap 'XStreamityActions' -> Action = 'ok'.
15:08:40.8157 { W } /usr/lib/python2.7/site-packages/twisted/python/util.py:815 untilConcludes 2023-11-23 15:08:40+0100 [-] /usr/lib/python2.7/site-packages/urllib3/connectionpool.py:1004: urllib3.exceptions.InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
15:08:40.8857 [ E ] ../../../git/src/serviceapp/extplayer.cpp:72 stderrAvail PlayerApp::stderrAvail: {"FF_ERROR":{"msg":"Invalid data found when processing input","code":-1094995529}}
{"PLAYBACK_OPEN":{"OutputName":"Output", "file":"https://xxxxxx:2083/player_api.php?username=xxxx&password=xxx&action=get_series_info&series_id=168888", "sts":-1}}

15:08:40.8858 [ E ] ../../../git/src/serviceapp/extplayer.cpp:8 handleJsonStr PlayerApp::handleJsonStr: {"FF_ERROR":{"msg":"Invalid data found when processing input","code":-1094995529}}
15:08:40.8858 [ E ] ../../../git/src/serviceapp/exteplayer3.cpp:410 handleJsonOutput ExtEPlayer3::handleJsonOutput - unhandled key "FF_ERROR"
15:08:40.8859 [   ] ../../../git/src/serviceapp/extplayer.cpp:8 handleJsonStr PlayerApp::handleJsonStr: {"PLAYBACK_OPEN":{"OutputName":"Output", "file":"https://xxxxxx:2083/player_api.php?username=xxxx&password=xxx&action=get_series_info&series_id=168888", "sts":-1}}
15:08:40.8859 [   ] ../../../git/src/serviceapp/exteplayer3.cpp:410 handleJsonOutput ExtEPlayer3::handleJsonOutput - unhandled key "PLAYBACK_OPEN"
15:08:40.8863 [   ] ../../../git/src/serviceapp/extplayer.cpp:82 stdoutAvail PlayerApp::stdoutAvail: Software decoder will be used for AAC codec
Software decoder will decode to stereo
Force rtmp protocol implementation
file: [https://xxxxxx:2083/player_api.php?username=xxxx&password=xxx&action=get_series_info&series_id=168888]

15:08:40.8874 [   ] base/ebase.cpp:280 processOneEvent [eMainloop::processOneEvent] unhandled POLLERR/HUP/NVAL for fd 44(16)
15:08:40.8874 [   ] base/ebase.cpp:280 processOneEvent [eMainloop::processOneEvent] unhandled POLLERR/HUP/NVAL for fd 44(16)
15:08:40.8874 [   ] base/ebase.cpp:280 processOneEvent [eMainloop::processOneEvent] unhandled POLLERR/HUP/NVAL for fd 44(16)
15:08:40.8875 [   ] base/ebase.cpp:280 processOneEvent [eMainloop::processOneEvent] unhandled POLLERR/HUP/NVAL for fd 44(16)
15:08:40.8875 [   ] base/ebase.cpp:280 processOneEvent [eMainloop::processOneEvent] unhandled POLLERR/HUP/NVAL for fd 44(16)
15:08:40.8875 [   ] base/ebase.cpp:280 processOneEvent [eMainloop::processOneEvent] unhandled POLLERR/HUP/NVAL for fd 44(16)
15:08:40.8876 [   ] base/ebase.cpp:280 processOneEvent [eMainloop::processOneEvent] unhandled POLLERR/HUP/NVAL for fd 44(16)
15:08:40.8876 [   ] base/ebase.cpp:280 processOneEvent [eMainloop::processOneEvent] unhandled POLLERR/HUP/NVAL for fd 44(16)
15:08:40.8876 [   ] base/ebase.cpp:280 processOneEvent [eMainloop::processOneEvent] unhandled POLLERR/HUP/NVAL for fd 44(16)
15:08:40.8877 [   ] base/ebase.cpp:280 processOneEvent [eMainloop::processOneEvent] unhandled POLLERR/HUP/NVAL for fd 44(16)
15:08:40.8877 [   ] base/ebase.cpp:280 processOneEvent [eMainloop::processOneEvent] unhandled POLLERR/HUP/NVAL for fd 44(16)
15:08:40.8877 [   ] base/ebase.cpp:280 processOneEvent [eMainloop::processOneEvent] unhandled POLLERR/HUP/NVAL for fd 44(16)
15:08:40.8877 [   ] base/ebase.cpp:280 processOneEvent [eMainloop::processOneEvent] unhandled POLLERR/HUP/NVAL for fd 44(16)
15:08:40.8878 [   ] base/ebase.cpp:280 processOneEvent [eMainloop::processOneEvent] unhandled POLLERR/HUP/NVAL for fd 44(16)
15:08:40.8878 [   ] base/ebase.cpp:280 processOneEvent [eMainloop::processOneEvent] unhandled POLLERR/HUP/NVAL for fd 44(16)
15:08:40.8878 [   ] base/ebase.cpp:280 processOneEvent [eMainloop::processOneEvent] unhandled POLLERR/HUP/NVAL for fd 44(16)
15:08:40.8879 [   ] base/ebase.cpp:280 processOneEvent [eMainloop::processOneEvent] unhandled POLLERR/HUP/NVAL for fd 44(16)
15:08:40.8879 [   ] base/ebase.cpp:280 processOneEvent [eMainloop::processOneEvent] unhandled POLLERR/HUP/NVAL for fd 44(16)
15:08:40.8879 [   ] base/ebase.cpp:280 processOneEvent [eMainloop::processOneEvent] unhandled POLLERR/HUP/NVAL for fd 44(16)
15:08:40.8880 [   ] base/ebase.cpp:280 processOneEvent [eMainloop::processOneEvent] unhandled POLLERR/HUP/NVAL for fd 44(16)
15:08:40.8880 [   ] base/ebase.cpp:280 processOneEvent [eMainloop::processOneEvent] unhandled POLLERR/HUP/NVAL for fd 44(16)
15:08:40.8880 [   ] base/ebase.cpp:280 processOneEvent [eMainloop::processOneEvent] unhandled POLLERR/HUP/NVAL for fd 44(16)
15:08:40.8880 [   ] base/ebase.cpp:280 processOneEvent [eMainloop::processOneEvent] unhandled POLLERR/HUP/NVAL for fd 44(16)
15:08:40.8881 [   ] base/ebase.cpp:280 processOneEvent [eMainloop::processOneEvent] unhandled POLLERR/HUP/NVAL for fd 44(16)
15:08:40.8881 [   ] base/ebase.cpp:280 processOneEvent [eMainloop::processOneEvent] unhandled POLLERR/HUP/NVAL for fd 44(16)
15:08:40.8881 [   ] base/ebase.cpp:280 processOneEvent [eMainloop::processOneEvent] unhandled POLLERR/HUP/NVAL for fd 44(16)
15:08:40.8882 [   ] base/ebase.cpp:280 processOneEvent [eMainloop::processOneEvent] unhandled POLLERR/HUP/NVAL for fd 44(16)
15:08:40.8882 [   ] base/ebase.cpp:280 processOneEvent [eMainloop::processOneEvent] unhandled POLLERR/HUP/NVAL for fd 44(16)
15:08:40.8882 [   ] base/ebase.cpp:280 processOneEvent [eMainloop::processOneEvent] unhandled POLLERR/HUP/NVAL for fd 44(16)
15:08:40.8883 [   ] base/ebase.cpp:280 processOneEvent [eMainloop::processOneEvent] unhandled POLLERR/HUP/NVAL for fd 44(16)
15:08:40.8884 [   ] ../../../git/src/serviceapp/extplayer.cpp:557 recvStopped PlayerBackend::recvStopped - retval = 0
15:08:40.8885 [   ] base/ebase.cpp:280 processOneEvent [eMainloop::processOneEvent] unhandled POLLERR/HUP/NVAL for fd 44(16)
15:08:40.8886 [   ] ../../../git/src/serviceapp/extplayer.cpp:534 thread_finished PlayerBackend::thread_finished
15:08:40.8950 {   } /usr/lib/python2.7/site-packages/twisted/python/util.py:815 untilConcludes 2023-11-23 15:08:40+0100 [-] Traceback (most recent call last):
15:08:40.8956 {   } /usr/lib/python2.7/site-packages/twisted/python/util.py:815 untilConcludes 2023-11-23 15:08:40+0100 [-]   File "/usr/lib/enigma2/python/Components/ActionMap.py", line 57, in action
15:08:40.8962 {   } /usr/lib/python2.7/site-packages/twisted/python/util.py:815 untilConcludes 2023-11-23 15:08:40+0100 [-]   File "/usr/lib/enigma2/python/Plugins/Extensions/XStreamity/channels.py", line 1703, in parentalCheck
15:08:40.8984 {   } /usr/lib/python2.7/site-packages/twisted/python/util.py:815 untilConcludes 2023-11-23 15:08:40+0100 [-]     self.next()
15:08:40.8989 {   } /usr/lib/python2.7/site-packages/twisted/python/util.py:815 untilConcludes 2023-11-23 15:08:40+0100 [-]   File "/usr/lib/enigma2/python/Plugins/Extensions/XStreamity/channels.py", line 1844, in next
15:08:40.9014 {   } /usr/lib/python2.7/site-packages/twisted/python/util.py:815 untilConcludes 2023-11-23 15:08:40+0100 [-]     self.createSetup()
15:08:40.9019 {   } /usr/lib/python2.7/site-packages/twisted/python/util.py:815 untilConcludes 2023-11-23 15:08:40+0100 [-]   File "/usr/lib/enigma2/python/Plugins/Extensions/XStreamity/channels.py", line 467, in createSetup
15:08:40.9031 {   } /usr/lib/python2.7/site-packages/twisted/python/util.py:815 untilConcludes 2023-11-23 15:08:40+0100 [-]     self.getLevel4()
15:08:40.9037 {   } /usr/lib/python2.7/site-packages/twisted/python/util.py:815 untilConcludes 2023-11-23 15:08:40+0100 [-]   File "/usr/lib/enigma2/python/Plugins/Extensions/XStreamity/channels.py", line 1057, in getLevel4
15:08:40.9053 {   } /usr/lib/python2.7/site-packages/twisted/python/util.py:815 untilConcludes 2023-11-23 15:08:40+0100 [-]     self.list4.append([index, str(title), str(stream_id), str(cover), str(plot), str(cast), str(director), str(genre), str(releasedate), str(rating), str(duration), str(container_extension), str(tmdb_id), str(next_url), str(shorttitle), str(last_modified), hidden])
15:08:40.9060 { E } /usr/lib/python2.7/site-packages/twisted/python/util.py:815 untilConcludes 2023-11-23 15:08:40+0100 [-] UnboundLocalError: local variable 'last_modified' referenced before assignment
15:08:40.9061 [ E ] python/python.cpp:210 call [ePyObject] (PyObject_CallObject(<bound method ActionMap.action of <Components.ActionMap.ActionMap instance at 0xac8d62b0>>,('XStreamityActions', 'ok')) failed)

dmesg

<6>hieth f9c30000.hieth eth0: Link is Down
<6>hieth f9c30000.hieth eth0: Link is Up - 100Mbps/Full - flow control rx/tx
<6>sh (18061): drop_caches: 1
<6>sh (18062): drop_caches: 2
<6>sh (18063): drop_caches: 3

**Comment by kiddac** [comment]
this has been corrected in last release.
