### ISSUE TITLE
Crash VTI 4.28

### ISSUE THREAD

**Issue by matze9090** [kiddac/XStreamity#41]
XStreamity crashes on VTI when i start a stream from playlist on version 4.28!

**Comment by matze9090** [comment]
I must rollback to version 4.24 to solve the problem!

**Comment by kiddac** [comment]
Is this still an issue? Nobody else seems to be reporting issues on vti at the moment.
 If so can you visit linuxsat forum, and post your crash log with your personal details removed from it. domain, username, password etc.

https://www.linuxsat-support.com/thread/147664-x-streamity-xtream-codes-iptv-player-new-thread/

**Comment by matze9090** [comment]
Yes it is!
Can i send you the crashlog via private Message?

**Comment by kiddac** [comment]
yews send me a crash log via linuxsat forum please

**Comment by matze9090** [comment]
[dvbapp2_crash_2024-01-12_22-26-15_1705094775.log](https://github.com/kiddac/XStreamity/files/13924270/dvbapp2_crash_2024-01-12_22-26-15_1705094775.log)

**Comment by matze9090** [comment]
> yews send me a crash log via linuxsat forum please

I have send the crashlog

**Comment by matze9090** [comment]
you get it?

**Comment by matze9090** [comment]
can you fix it?

**Comment by matze9090** [comment]
thank you, 4.31 works now!
