### ISSUE TITLE
Issue with next/previous on films and series

### ISSUE THREAD

**Issue by nonameboy007** [kiddac/XStreamity#42]
Hi @kiddac ,

first of all, Best wishes for this new year.  health, happiness and all the best.  😀 

I have a little question about the plugin.

On live stream,  I can use next/previous button (or up/down) to change a channel. But it's not working on series or vod. Does its the normal behavior? Or I have an issue with my openatv image? 

It will be a great feature to have this, and the ability to have an autoplay next option for series.

Thanks for your reply  👍.

**Comment by kiddac** [comment]
Its not a bug, It was actually designed that way. Because you are not going to zap like you would on live tv.
Vod is pointless. I see your point with series, but for the sake of pressing... exit, down and ok to play the next stream. Do you really need an autoplay for series.

**Comment by nonameboy007** [comment]
Hi Kiddac, 

Thanks for your return,

Yes I think that an autoplay options for series could be a good feature, like an activation by pressing the 0 button for example, and the ability to do next or previous episode by > or < or Ch+ or Ch- button could be great. 

One button action better than three no?

Thanks again
