### ISSUE TITLE
Request contact

### ISSUE THREAD

**Issue by marK55555mark** [kiddac/XStreamity#43]
This is for contact u, how can? i want customize ur app with u, how can contact u?

**Comment by matze9090** [comment]
https://www.linuxsat-support.com/thread/147664-x-streamity-xtream-codes-iptv-player-new-thread/

**Comment by kiddac** [comment]
I don't affiliate with any iptv providers. And anyone that makes dodgy versions of my plugin that is locked down to a provider, I write code to find those rogue plugins and delete them. 
The nature of my work means nothing illegal can be in any of my plugins.

You never said you were a provider or where going to do that. But I am just warning people my rules.

Any other questions you can find me on linuxsat forum.
