### ISSUE TITLE
How I install this?

### ISSUE THREAD

**Issue by Ash3781** [kiddac/XStreamity#52]
Hey, I have not done much with my dreambox and have yet to install an package using an zip file. I have found different sites that claim that they host .deb files for this, however I don't trust them and also would have to be logged in to download those files, so I'd rather be able to understand how to install this with the zip file

**Comment by kiddac** [comment]
All my official threads and source ipks / deb files live on linuxsat forum

https://www.linuxsat-support.com/board/1462-enigma2-kiddac/

and yes you have to sign up to that site if you want to download my plugins from there. 

On github. All my plugins have ipk release versions. As seen on the right hand side of githib on desktop view. You can download them. 
Extract them with 7zip software and manually copy the folder usr and etc folders over to your box. 
It it much better if you install the correct .deb version from linuxsat forum though,
